In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('bank dataset 1.csv')
print(df.head())

   customer_id   age  gender marital_status education_level  annual_income  \
0    427741615  30.0  Female        Widowed          Master       14073.58
1    228500249  35.0    Male         Single        Bachelor            NaN
2    396233462  59.0    Male        Married          Master       16764.51
3    909211459  26.0    Male        Married          Master       53460.55
4    982980455  59.0    Male         Single        Bachelor       66520.40

   loan_amount  credit_score  employment_years employment_type  ...  \
0    147079.61         803.0              29.5   Self-employed  ...
1     14771.04         577.0              33.6       Part-time  ...
2    194804.70         790.0              40.0       Full-time  ...
3    138636.74         684.0              27.7       Part-time  ...
4     79776.32         662.0              37.7       Full-time  ...

  flag_feature_173 category_feature_174  numeric_feature_175  \
0              0.0                    A               521.86
1              NaN                    E              1011.11
2              0.0                    A               906.42
3              0.0                    B              1234.89
4              0.0                    A               656.23

   flag_feature_176  numeric_feature_177  flag_feature_178 flag_feature_179  \
0               0.0              1090.84               0.0              1.0
1               0.0               880.80               0.0              0.0
2               NaN              1134.84               0.0              1.0
3               0.0               522.34               0.0              0.0
4               0.0               492.42               0.0              1.0

  category_feature_180  flag_feature_181 category_feature_182
0                    C               0.0                    E
1                    A               0.0                    A
2                    D               0.0                    A
3                    C               1.0                    A
4                    A               NaN                    B

[5 rows x 200 columns]

In [3]:
df.describe()

,customer_id,age,annual_income,loan_amount,credit_score,employment_years,debt_to_income_ratio,existing_loans,loan_term_months,interest_rate,...,flag_feature_168,ratio_feature_169,numeric_feature_171,flag_feature_173,numeric_feature_175,flag_feature_176,numeric_feature_177,flag_feature_178,flag_feature_179,flag_feature_181
count,1.000000e+04,9290.000000,9275.000000,9316.000000,9277.000000,9278.000000,9274.000000,9275.000000,9298.000000,9270.000000,...,9284.000000,9289.000000,9325.000000,9337.000000,9238.000000,9340.000000,9297.000000,9283.000000,9300.00000,9282.000000
mean,5.460793e+08,46.021098,39570.355780,249805.891756,678.057238,19.888640,0.434236,1.402049,119.145623,13.890683,...,0.293516,0.498159,996.154784,0.300418,1002.836779,0.303640,997.605101,0.299472,0.30043,0.298535
std,2.594427e+08,16.468364,26279.408111,144409.498380,83.579935,11.583725,0.240208,1.180212,110.985090,6.531589,...,0.455397,0.286808,300.110682,0.458464,300.473568,0.459854,302.712710,0.458052,0.45847,0.457640
min,1.000280e+08,18.000000,3240.190000,1066.510000,371.000000,0.000000,0.010000,0.000000,12.000000,2.500000,...,0.000000,0.000000,-98.050000,0.000000,-55.850000,0.000000,-169.160000,0.000000,0.00000,0.000000
25%,3.216843e+08,32.000000,22038.360000,123805.420000,621.000000,9.700000,0.228000,1.000000,36.000000,8.210000,...,0.000000,0.249700,791.040000,0.000000,803.070000,0.000000,792.610000,0.000000,0.00000,0.000000
50%,5.461803e+08,46.000000,33169.010000,247723.575000,679.000000,19.700000,0.433000,1.000000,60.000000,13.920000,...,0.000000,0.501200,999.830000,0.000000,1005.560000,0.000000,997.500000,0.000000,0.00000,0.000000
75%,7.716024e+08,60.000000,49248.985000,377296.127500,735.000000,29.900000,0.643000,2.000000,180.000000,19.550000,...,1.000000,0.744100,1198.310000,1.000000,1205.350000,1.000000,1201.690000,1.000000,1.00000,1.000000
max,9.999141e+08,74.000000,329105.270000,499964.710000,850.000000,40.000000,0.850000,8.000000,360.000000,25.000000,...,1.000000,0.999900,2170.530000,1.000000,2048.290000,1.000000,2078.010000,1.000000,1.00000,1.000000

In [4]:
print(df.shape)
print(df.info())

(10000, 200)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Columns: 200 entries, customer_id to category_feature_182
dtypes: float64(149), int64(1), object(50)
memory usage: 15.3+ MB
None

In [5]:
df.columns.tolist()

['customer_id',
 'age',
 'gender',
 'marital_status',
 'education_level',
 'annual_income',
 'loan_amount',
 'credit_score',
 'employment_years',
 'employment_type',
 'loan_purpose',
 'home_ownership',
 'debt_to_income_ratio',
 'existing_loans',
 'loan_term_months',
 'interest_rate',
 'loan_status',
 'application_date',
 'flag_feature_1',
 'category_feature_2',
 'ratio_feature_3',
 'numeric_feature_4',
 'numeric_feature_5',
 'numeric_feature_6',
 'flag_feature_7',
 'numeric_feature_8',
 'category_feature_9',
 'numeric_feature_10',
 'numeric_feature_11',
 'ratio_feature_12',
 'ratio_feature_13',
 'numeric_feature_14',
 'category_feature_15',
 'numeric_feature_16',
 'ratio_feature_17',
 'numeric_feature_18',
 'numeric_feature_19',
 'category_feature_20',
 'numeric_feature_21',
 'ratio_feature_22',
 'numeric_feature_23',
 'category_feature_24',
 'numeric_feature_25',
 'category_feature_26',
 'flag_feature_27',
 'ratio_feature_28',
 'category_feature_29',
 'numeric_feature_30',
 'flag_feature_31',
 'category_feature_32',
 'numeric_feature_33',
 'category_feature_34',
 'flag_feature_35',
 'numeric_feature_36',
 'numeric_feature_37',
 'numeric_feature_38',
 'category_feature_39',
 'ratio_feature_40',
 'ratio_feature_41',
 'flag_feature_42',
 'ratio_feature_43',
 'ratio_feature_44',
 'flag_feature_45',
 'flag_feature_46',
 'category_feature_47',
 'category_feature_48',
 'category_feature_49',
 'numeric_feature_50',
 'flag_feature_51',
 'ratio_feature_52',
 'flag_feature_53',
 'ratio_feature_54',
 'flag_feature_55',
 'numeric_feature_56',
 'numeric_feature_57',
 'ratio_feature_58',
 'category_feature_59',
 'flag_feature_60',
 'category_feature_61',
 'ratio_feature_62',
 'ratio_feature_63',
 'numeric_feature_64',
 'numeric_feature_65',
 'flag_feature_66',
 'flag_feature_67',
 'flag_feature_68',
 'ratio_feature_69',
 'ratio_feature_70',
 'numeric_feature_71',
 'numeric_feature_72',
 'flag_feature_73',
 'ratio_feature_74',
 'numeric_feature_75',
 'numeric_feature_76',
 'flag_feature_77',
 'ratio_feature_78',
 'flag_feature_79',
 'ratio_feature_80',
 'flag_feature_81',
 'numeric_feature_82',
 'ratio_feature_83',
 'flag_feature_84',
 'category_feature_85',
 'numeric_feature_86',
 'ratio_feature_87',
 'numeric_feature_88',
 'category_feature_89',
 'flag_feature_90',
 'category_feature_91',
 'category_feature_92',
 'ratio_feature_93',
 'ratio_feature_94',
 'ratio_feature_95',
 'numeric_feature_96',
 'category_feature_97',
 'ratio_feature_98',
 'ratio_feature_99',
 'flag_feature_100',
 'category_feature_101',
 'ratio_feature_102',
 'flag_feature_103',
 'ratio_feature_104',
 'flag_feature_105',
 'ratio_feature_106',
 'category_feature_107',
 'category_feature_108',
 'numeric_feature_109',
 'category_feature_110',
 'category_feature_111',
 'category_feature_112',
 'category_feature_113',
 'numeric_feature_114',
 'ratio_feature_115',
 'category_feature_116',
 'flag_feature_117',
 'flag_feature_118',
 'numeric_feature_119',
 'category_feature_120',
 'ratio_feature_121',
 'flag_feature_122',
 'flag_feature_123',
 'category_feature_124',
 'numeric_feature_125',
 'ratio_feature_126',
 'ratio_feature_127',
 'ratio_feature_128',
 'ratio_feature_129',
 'ratio_feature_130',
 'numeric_feature_131',
 'ratio_feature_132',
 'ratio_feature_133',
 'numeric_feature_134',
 'category_feature_135',
 'numeric_feature_136',
 'category_feature_137',
 'ratio_feature_138',
 'category_feature_139',
 'numeric_feature_140',
 'flag_feature_141',
 'numeric_feature_142',
 'numeric_feature_143',
 'numeric_feature_144',
 'category_feature_145',
 'numeric_feature_146',
 'flag_feature_147',
 'numeric_feature_148',
 'numeric_feature_149',
 'category_feature_150',
 'ratio_feature_151',
 'category_feature_152',
 'flag_feature_153',
 'flag_feature_154',
 'flag_feature_155',
 'ratio_feature_156',
 'numeric_feature_157',
 'numeric_feature_158',
 'ratio_feature_159',
 'ratio_feature_160',
 'ratio_feature_161',
 'ratio_feature_162',
 'flag_feature_163',
 'numeric_feature_164',
 'category_feature_165',
 'numeric_feature_166',
 'flag_feature_167',
 'flag_feature_168',
 'ratio_feature_169',
 'category_feature_170',
 'numeric_feature_171',
 'category_feature_172',
 'flag_feature_173',
 'category_feature_174',
 'numeric_feature_175',
 'flag_feature_176',
 'numeric_feature_177',
 'flag_feature_178',
 'flag_feature_179',
 'category_feature_180',
 'flag_feature_181',
 'category_feature_182']

In [6]:
main_cols = [
    "customer_id", 
    "age", "gender",
    "marital_status", 
    "education_level",
    "annual_income", 
    "loan_amount", 
    "credit_score", 
    "employment_years",
    "employment_type", 
    "loan_purpose", 
    "home_ownership",
    "debt_to_income_ratio", 
    "existing_loans", 
    "loan_term_months",
    "interest_rate", 
    "loan_status", 
    "application_date"
]
df[main_cols].head()

,customer_id,age,gender,marital_status,education_level,annual_income,loan_amount,credit_score,employment_years,employment_type,loan_purpose,home_ownership,debt_to_income_ratio,existing_loans,loan_term_months,interest_rate,loan_status,application_date
0,427741615,30.0,Female,Widowed,Master,14073.58,147079.61,803.0,29.5,Self-employed,Business,Mortgage,0.383,1.0,240.0,22.95,NaN,2016-02-21
1,228500249,35.0,Male,Single,Bachelor,NaN,14771.04,577.0,33.6,Part-time,Personal,Mortgage,0.400,5.0,48.0,14.85,Approved,2019-07-23
2,396233462,59.0,Male,Married,Master,16764.51,194804.70,790.0,40.0,Full-time,NaN,Own,0.177,2.0,360.0,16.87,Rejected,2023-03-01
3,909211459,26.0,Male,Married,Master,53460.55,138636.74,684.0,27.7,Part-time,Personal,Own,0.216,1.0,240.0,11.41,Approved,2016-06-08
4,982980455,59.0,Male,Single,Bachelor,66520.40,79776.32,662.0,37.7,Full-time,Home,Own,0.067,1.0,12.0,6.17,Approved,2023-05-17

In [7]:
# duplicate
print("duplicate rows:", df.duplicated().sum())
print("duplicate columns:", df.columns.duplicated().sum())

duplicate rows: 0
duplicate columns: 0

In [8]:
missing = df[main_cols].isnull().sum().sort_values(ascending=False)
missing_pct = (df[main_cols].isnull().mean() * 100).sort_values(ascending=False)
missing_summary = pd.DataFrame({"missing": missing, "missing_pct": missing_pct})
print(missing_summary)

                      missing  missing_pct
application_date          735         7.35
interest_rate             730         7.30
debt_to_income_ratio      726         7.26
existing_loans            725         7.25
annual_income             725         7.25
credit_score              723         7.23
employment_years          722         7.22
marital_status            721         7.21
home_ownership            718         7.18
age                       710         7.10
loan_term_months          702         7.02
loan_purpose              701         7.01
gender                    700         7.00
employment_type           698         6.98
education_level           693         6.93
loan_amount               684         6.84
loan_status               676         6.76
customer_id                 0         0.00

In [9]:
print(df[main_cols].describe())

        customer_id          age  annual_income    loan_amount  credit_score  \
count  1.000000e+04  9290.000000    9275.000000    9316.000000   9277.000000
mean   5.460793e+08    46.021098   39570.355780  249805.891756    678.057238
std    2.594427e+08    16.468364   26279.408111  144409.498380     83.579935
min    1.000280e+08    18.000000    3240.190000    1066.510000    371.000000
25%    3.216843e+08    32.000000   22038.360000  123805.420000    621.000000
50%    5.461803e+08    46.000000   33169.010000  247723.575000    679.000000
75%    7.716024e+08    60.000000   49248.985000  377296.127500    735.000000
max    9.999141e+08    74.000000  329105.270000  499964.710000    850.000000

       employment_years  debt_to_income_ratio  existing_loans  \
count       9278.000000           9274.000000     9275.000000
mean          19.888640              0.434236        1.402049
std           11.583725              0.240208        1.180212
min            0.000000              0.010000        0.000000
25%            9.700000              0.228000        1.000000
50%           19.700000              0.433000        1.000000
75%           29.900000              0.643000        2.000000
max           40.000000              0.850000        8.000000

       loan_term_months  interest_rate
count       9298.000000    9270.000000
mean         119.145623      13.890683
std          110.985090       6.531589
min           12.000000       2.500000
25%           36.000000       8.210000
50%           60.000000      13.920000
75%          180.000000      19.550000
max          360.000000      25.000000

In [10]:
#taget: loan_status column
df = df.dropna(subset=["loan_status"])

In [11]:
df["loan_status"].value_counts()

loan_status
Approved    6743
Rejected    2581
Name: count, dtype: int64

In [12]:
df[main_cols].isnull().sum().sort_values(ascending=False)

application_date        696
interest_rate           681
credit_score            678
employment_years        676
annual_income           674
home_ownership          673
debt_to_income_ratio    672
marital_status          671
existing_loans          671
age                     670
gender                  660
loan_purpose            658
loan_term_months        656
education_level         652
employment_type         651
loan_amount             632
loan_status               0
customer_id               0
dtype: int64

In [13]:
#numeric columns
numeric_cols = ["age", "annual_income", "loan_amount", "credit_score", "employment_years", "debt_to_income_ratio", "existing_loans", "loan_term_months", "interest_rate"]

In [14]:
for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower) | (df[col] > upper)]

print("outlier:", outliers.shape[0])

outlier: 0

In [15]:
for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

In [16]:
#categorical columns
categorical_cols = [
    "gender", "marital_status", "education_level",
    "employment_type", "loan_purpose", "home_ownership"
]
for col in categorical_cols:
    df[col] = df[col].fillna("Unknown")
    df[col] = df[col].astype("string").str.strip().str.lower()

In [17]:
#date column
#convert to datetime
df["application_date"] = pd.to_datetime(df["application_date"], errors="coerce")

df = df.drop(columns=["application_date"])

In [18]:
main_cols_updated = [
    "customer_id", 
    "age", 
    "gender", 
    "marital_status", 
    "education_level",
    "annual_income", 
    "loan_amount", 
    "credit_score", 
    "employment_years",
    "employment_type", 
    "loan_purpose", 
    "home_ownership",
    "debt_to_income_ratio", 
    "existing_loans", 
    "loan_term_months",
    "interest_rate", 
    "loan_status"
]

In [19]:
df_cleaned = df[main_cols_updated]

In [20]:
df_cleaned.isnull().sum().sort_values(ascending=False)

customer_id             0
employment_type         0
interest_rate           0
loan_term_months        0
existing_loans          0
debt_to_income_ratio    0
home_ownership          0
loan_purpose            0
employment_years        0
age                     0
credit_score            0
loan_amount             0
annual_income           0
education_level         0
marital_status          0
gender                  0
loan_status             0
dtype: int64

In [21]:
df_cleaned.info()
df_cleaned.shape

<class 'pandas.core.frame.DataFrame'>
Index: 9324 entries, 1 to 9999
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           9324 non-null   int64
 1   age                   9324 non-null   float64
 2   gender                9324 non-null   string
 3   marital_status        9324 non-null   string
 4   education_level       9324 non-null   string
 5   annual_income         9324 non-null   float64
 6   loan_amount           9324 non-null   float64
 7   credit_score          9324 non-null   float64
 8   employment_years      9324 non-null   float64
 9   employment_type       9324 non-null   string
 10  loan_purpose          9324 non-null   string
 11  home_ownership        9324 non-null   string
 12  debt_to_income_ratio  9324 non-null   float64
 13  existing_loans        9324 non-null   float64
 14  loan_term_months      9324 non-null   float64
 15  interest_rate         9324 non-null   float64
 16  loan_status           9324 non-null   object
dtypes: float64(9), int64(1), object(1), string(6)
memory usage: 1.3+ MB

(9324, 17)

In [22]:
df_cleaned.head()

,customer_id,age,gender,marital_status,education_level,annual_income,loan_amount,credit_score,employment_years,employment_type,loan_purpose,home_ownership,debt_to_income_ratio,existing_loans,loan_term_months,interest_rate,loan_status
1,228500249,35.0,male,single,bachelor,33257.31,14771.04,577.0,33.6,part-time,personal,mortgage,0.400,5.0,48.0,14.85,Approved
2,396233462,59.0,male,married,master,16764.51,194804.70,790.0,40.0,full-time,unknown,own,0.177,2.0,360.0,16.87,Rejected
3,909211459,26.0,male,married,master,53460.55,138636.74,684.0,27.7,part-time,personal,own,0.216,1.0,240.0,11.41,Approved
4,982980455,59.0,male,single,bachelor,66520.40,79776.32,662.0,37.7,full-time,home,own,0.067,1.0,12.0,6.17,Approved
5,349162937,40.0,male,single,high school,21824.42,121541.37,560.0,5.5,part-time,car,own,0.432,1.0,120.0,18.68,Approved

In [23]:
cat_cols = [
    "gender",
    "marital_status",
    "education_level",
    "employment_type",
    "loan_purpose",
    "home_ownership"
]

summary_cat = pd.DataFrame({
    "column": cat_cols,
    "n_unique": [df_cleaned[col].nunique(dropna=False) for col in cat_cols],
    "unique_values": [df_cleaned[col].drop_duplicates().tolist() for col in cat_cols]
})

pd.set_option("display.max_colwidth", None)
print(summary_cat.to_string(index=False))

         column  n_unique                                                unique_values
         gender         4                               [male, female, unknown, other]
 marital_status         5                [single, married, unknown, divorced, widowed]
education_level         6       [bachelor, master, high school, phd, unknown, diploma]
employment_type         5   [part-time, full-time, self-employed, unemployed, unknown]
   loan_purpose         7 [personal, unknown, home, car, business, education, medical]
 home_ownership         5                        [mortgage, own, unknown, other, rent]

### Preprocessing

In [24]:
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.datasets import make_classification

from sklearn.dummy import DummyClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

from sklearn.ensemble import AdaBoostClassifier


from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

import warnings
warnings.filterwarnings("ignore")

In [25]:
df_pre = df_cleaned.drop(columns=["customer_id"])
x = df_pre.drop(columns=["loan_status"])
y = df_pre["loan_status"]

y = df_pre["loan_status"].str.strip().str.lower()
y = y.map({"rejected": 0, "approved": 1})

In [26]:
#split train, test
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42, stratify=y)

cat_cols = x_train.select_dtypes(include=["object", "string"]).columns.tolist()
num_cols = x_train.select_dtypes(include=["int64", "float64"]).columns.tolist()

#scale numeric features
scaler = StandardScaler()
x_train_num = pd.DataFrame(scaler.fit_transform(x_train[num_cols]), 
                           columns=num_cols, index=x_train.index
                           )
x_test_num = pd.DataFrame(scaler.transform(x_test[num_cols]),
                          columns=num_cols, index=x_test.index
                          )


#encode categorical features
x_train_cat = pd.get_dummies(x_train[cat_cols], drop_first=True, dtype=int)
x_test_cat = pd.get_dummies(x_test[cat_cols], drop_first=True, dtype=int)

# merge numeric and categorical features

x_train = pd.concat([x_train_num, x_train_cat], axis=1)
x_test = pd.concat([x_test_num, x_test_cat], axis=1)

#undersampling
from imblearn.under_sampling import RandomUnderSampler

rus = RandomUnderSampler(random_state=42, sampling_strategy=0.6)
x_train, y_train = rus.fit_resample(x_train, y_train)

In [27]:
df_cleaned.value_counts()

customer_id  age   gender  marital_status  education_level  annual_income  loan_amount  credit_score  employment_years  employment_type  loan_purpose  home_ownership  debt_to_income_ratio  existing_loans  loan_term_months  interest_rate  loan_status
100359286    56.0  male    married         unknown          32668.14       110189.69    679.0         0.1               self-employed    car           own             0.186                 1.0             240.0             17.82          Approved       1
692660226    34.0  male    divorced        high school      20593.46       271703.80    561.0         4.6               full-time        business      rent            0.353                 2.0             24.0              17.39          Approved       1
694651012    49.0  male    married         bachelor         38881.25       284646.73    508.0         29.2              full-time        home          mortgage        0.432                 1.0             24.0              24.69          Approved       1
694754289    68.0  male    single          bachelor         6337.85        93001.26     516.0         21.4              unemployed       car           rent            0.578                 1.0             60.0              17.60          Approved       1
694882683    74.0  female  single          high school      33257.31       168678.20    686.0         14.9              full-time        personal      own             0.360                 0.0             24.0              16.48          Rejected       1
                                                                                                                                                                                                                                                            ..
395278221    33.0  female  single          bachelor         14764.63       487926.27    735.0         25.4              full-time        home          rent            0.305                 0.0             240.0             2.67           Rejected       1
395327908    39.0  male    married         high school      36395.03       10486.50     679.0         20.2              part-time        personal      mortgage        0.165                 4.0             360.0             18.10          Approved       1
395373015    69.0  male    widowed         master           33257.31       91656.86     521.0         33.2              full-time        car           own             0.538                 1.0             12.0              3.78           Approved       1
395426127    46.0  female  single          bachelor         15822.29       178558.72    775.0         14.0              full-time        car           own             0.339                 0.0             12.0              13.88          Approved       1
999914076    35.0  male    unknown         high school      48115.61       45597.71     795.0         37.3              full-time        business      own             0.067                 3.0             180.0             15.38          Approved       1
Name: count, Length: 9324, dtype: int64

In [28]:
label_counts = y_train.value_counts()
label_pct    = y_train.value_counts(normalize=True) * 100

summary = pd.DataFrame({
    "Count": label_counts,
    "Percent (%)": label_pct.round(2)
})
print(summary)

             Count  Percent (%)
loan_status
1             3441         62.5
0             2065         37.5

In [29]:
y_train.head()

7508    0
6136    0
8065    0
7153    0
7855    0
Name: loan_status, dtype: int64

In [30]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5506 entries, 7508 to 5913
Data columns (total 35 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   age                            5506 non-null   float64
 1   annual_income                  5506 non-null   float64
 2   loan_amount                    5506 non-null   float64
 3   credit_score                   5506 non-null   float64
 4   employment_years               5506 non-null   float64
 5   debt_to_income_ratio           5506 non-null   float64
 6   existing_loans                 5506 non-null   float64
 7   loan_term_months               5506 non-null   float64
 8   interest_rate                  5506 non-null   float64
 9   gender_male                    5506 non-null   int32
 10  gender_other                   5506 non-null   int32
 11  gender_unknown                 5506 non-null   int32
 12  marital_status_married         5506 non-null   int32
 13  marital_status_single          5506 non-null   int32
 14  marital_status_unknown         5506 non-null   int32
 15  marital_status_widowed         5506 non-null   int32
 16  education_level_diploma        5506 non-null   int32
 17  education_level_high school    5506 non-null   int32
 18  education_level_master         5506 non-null   int32
 19  education_level_phd            5506 non-null   int32
 20  education_level_unknown        5506 non-null   int32
 21  employment_type_part-time      5506 non-null   int32
 22  employment_type_self-employed  5506 non-null   int32
 23  employment_type_unemployed     5506 non-null   int32
 24  employment_type_unknown        5506 non-null   int32
 25  loan_purpose_car               5506 non-null   int32
 26  loan_purpose_education         5506 non-null   int32
 27  loan_purpose_home              5506 non-null   int32
 28  loan_purpose_medical           5506 non-null   int32
 29  loan_purpose_personal          5506 non-null   int32
 30  loan_purpose_unknown           5506 non-null   int32
 31  home_ownership_other           5506 non-null   int32
 32  home_ownership_own             5506 non-null   int32
 33  home_ownership_rent            5506 non-null   int32
 34  home_ownership_unknown         5506 non-null   int32
dtypes: float64(9), int32(26)
memory usage: 989.4 KB

In [31]:
x_train.head()

,age,annual_income,loan_amount,credit_score,employment_years,debt_to_income_ratio,existing_loans,loan_term_months,interest_rate,gender_male,...,loan_purpose_car,loan_purpose_education,loan_purpose_home,loan_purpose_medical,loan_purpose_personal,loan_purpose_unknown,home_ownership_other,home_ownership_own,home_ownership_rent,home_ownership_unknown
7508,-0.579879,-0.682773,1.315340,-0.612682,-0.732423,0.534329,1.439927,-0.726927,-0.227445,0,...,0,0,0,0,1,0,0,0,0,0
6136,1.570477,-0.393070,0.395075,0.634264,0.983520,-0.005199,-0.322241,-0.615172,0.042136,1,...,0,0,0,0,0,0,0,0,1,0
8065,-1.655056,-0.878532,-1.779270,2.130598,-1.154670,-1.131733,0.558843,0.055361,-1.324910,1,...,0,0,0,1,0,0,0,0,0,0
7153,1.570477,-0.826859,-0.178892,1.557003,-1.531998,0.214929,-0.322241,-0.615172,-0.557641,0,...,0,0,0,0,1,0,0,0,0,1
7855,-1.781548,-0.671535,-0.958553,0.596855,-1.729646,-1.753269,-0.322241,-0.503416,-1.053734,1,...,0,0,1,0,0,0,0,0,0,0

In [32]:
x_test.head()

,age,annual_income,loan_amount,credit_score,employment_years,debt_to_income_ratio,existing_loans,loan_term_months,interest_rate,gender_male,...,loan_purpose_car,loan_purpose_education,loan_purpose_home,loan_purpose_medical,loan_purpose_personal,loan_purpose_unknown,home_ownership_other,home_ownership_own,home_ownership_rent,home_ownership_unknown
9151,-0.073912,-0.475133,-1.351510,0.010791,1.558496,-0.730324,-0.322241,-0.950438,-0.139711,0,...,1,0,0,0,0,0,0,0,1,0
2470,-1.591811,0.513320,-0.021327,0.135486,1.154216,0.650867,1.439927,1.172915,-1.795480,1,...,0,1,0,0,0,0,0,1,0,0
5446,-1.338828,1.297539,-0.811282,-0.587743,0.489401,-0.000882,0.558843,-0.503416,-1.691795,1,...,0,0,1,0,0,0,0,0,1,0
4212,-0.896107,-0.162024,1.676456,-0.039087,-0.633599,0.119972,-0.322241,-0.726927,-0.453956,1,...,0,0,0,0,0,0,0,1,0,0
7510,0.432054,0.923490,0.648891,0.397344,0.363625,1.773085,-0.322241,0.614138,-0.554451,0,...,0,0,0,0,0,0,0,1,0,0

### training

In [33]:
# base model (dummy classifier)
model_base= DummyClassifier(strategy="most_frequent")
model_base.fit(x_train, y_train)

y_pre_base = model_base.predict(x_test)

print("Accuracy:", accuracy_score(y_test, y_pre_base))
print(confusion_matrix(y_test, y_pre_base))
print(classification_report(y_test, y_pre_base))

Accuracy: 0.7233243967828418
[[   0  516]
 [   0 1349]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       516
           1       0.72      1.00      0.84      1349

    accuracy                           0.72      1865
   macro avg       0.36      0.50      0.42      1865
weighted avg       0.52      0.72      0.61      1865

In [34]:
# Logistic Regression
prams_lr = {
       "C": [0.01, 0.1, 1, 10, 100],
    "penalty": ["l2"],
    "solver": ["lbfgs", "liblinear"],
    "class_weight": [None, "balanced"]
}

grid_lr = GridSearchCV(
    estimator=LogisticRegression(
        class_weight="balanced",
        random_state=42,
        max_iter=1000
    ),
    param_grid=prams_lr,
    scoring="f1",
    cv=5,
    n_jobs=-1
)
grid_lr.fit(x_train, y_train)
model_lr = grid_lr.best_estimator_

y_pre_lr = model_lr.predict(x_test)

print("Accuracy:", accuracy_score(y_test, y_pre_lr))
print(confusion_matrix(y_test, y_pre_lr))
print(classification_report(y_test, y_pre_lr))

Accuracy: 0.7227882037533512
[[   0  516]
 [   1 1348]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       516
           1       0.72      1.00      0.84      1349

    accuracy                           0.72      1865
   macro avg       0.36      0.50      0.42      1865
weighted avg       0.52      0.72      0.61      1865

In [35]:
# decision tree

params_dt = {
    "criterion": ["gini", "entropy"],
    "max_depth": [3, 5, 10, 15],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 5],
    "class_weight": ["balanced"]
}

grid_dt = GridSearchCV(
    estimator=DecisionTreeClassifier(random_state=42),
    param_grid=params_dt,
    scoring="f1_macro",  
    cv=5,
    n_jobs=-1
)

grid_dt.fit(x_train, y_train)
model_dt = grid_dt.best_estimator_

y_pre_dt = model_dt.predict(x_test)

print("Accuracy:", accuracy_score(y_test, y_pre_dt))
print(confusion_matrix(y_test, y_pre_dt))
print(classification_report(y_test, y_pre_dt))

Accuracy: 0.5554959785522788
[[237 279]
 [550 799]]
              precision    recall  f1-score   support

           0       0.30      0.46      0.36       516
           1       0.74      0.59      0.66      1349

    accuracy                           0.56      1865
   macro avg       0.52      0.53      0.51      1865
weighted avg       0.62      0.56      0.58      1865

In [36]:
#random forest
params_rf = {
     "n_estimators": [100, 200, 300, 500],
    "criterion": ["gini", "entropy"],
    "max_depth": [None, 5, 10, 15, 20],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 5],
    "max_features": ["sqrt", "log2"],
    "class_weight": ["balanced"]
}

random_rf = RandomizedSearchCV(
     estimator=RandomForestClassifier(random_state=42),  
    param_distributions=params_rf,                      
    n_iter=30,
    scoring="f1_macro",
    cv=5,
    random_state=42,
    n_jobs=-1
)

random_rf.fit(x_train, y_train)

model_rf = random_rf.best_estimator_
y_pre_rf = model_rf.predict(x_test)

print("Accuracy:", accuracy_score(y_test, y_pre_rf))
print(confusion_matrix(y_test, y_pre_rf))
print(classification_report(y_test, y_pre_rf))

Accuracy: 0.5651474530831099
[[222 294]
 [517 832]]
              precision    recall  f1-score   support

           0       0.30      0.43      0.35       516
           1       0.74      0.62      0.67      1349

    accuracy                           0.57      1865
   macro avg       0.52      0.52      0.51      1865
weighted avg       0.62      0.57      0.58      1865

In [37]:
from xgboost import XGBClassifier
# XGBoost
scale = (y_train == 0).sum() / (y_train == 1).sum()
params_xgb = {
     "n_estimators": [100, 200, 300, 500],
    "learning_rate": [0.01, 0.05, 0.1, 0.2],
    "max_depth": [3, 5, 7, 10],
    "min_child_weight": [1, 3, 5],
    "subsample": [0.6, 0.8, 1.0],
    "colsample_bytree": [0.6, 0.8, 1.0],
    "gamma": [0, 0.1, 0.3],
    "reg_alpha": [0, 0.01, 0.1],
    "reg_lambda": [0.1, 1, 10]
}

random_xgb = RandomizedSearchCV(
    estimator=XGBClassifier(
        random_state=42,
        objective="binary:logistic",
        eval_metric="logloss",
        scale_pos_weight=scale,
        n_jobs=-1
    ),
    param_distributions=params_xgb,
    n_iter=30,
    scoring="f1_macro",
    cv=5,
    random_state=42,
    n_jobs=-1
)

random_xgb.fit(x_train, y_train)

model_xgb = random_xgb.best_estimator_
y_pre_xgb = model_xgb.predict(x_test)

print("Accuracy:", accuracy_score(y_test, y_pre_xgb))
print(confusion_matrix(y_test, y_pre_xgb))
print(classification_report(y_test, y_pre_xgb))

Accuracy: 0.6075067024128686
[[204 312]
 [420 929]]
              precision    recall  f1-score   support

           0       0.33      0.40      0.36       516
           1       0.75      0.69      0.72      1349

    accuracy                           0.61      1865
   macro avg       0.54      0.54      0.54      1865
weighted avg       0.63      0.61      0.62      1865

In [38]:
from sklearn.ensemble import AdaBoostClassifier
#AdaBoost
params_ada = {
    "n_estimators": [50, 100, 200, 300],
    "learning_rate": [0.01, 0.05, 0.1, 0.5, 1.0],
    "estimator": [
        DecisionTreeClassifier(max_depth=1, class_weight="balanced", random_state=42),
        DecisionTreeClassifier(max_depth=2, class_weight="balanced", random_state=42),
        DecisionTreeClassifier(max_depth=3, class_weight="balanced", random_state=42)
    ]
}

random_ada = RandomizedSearchCV(
    estimator=AdaBoostClassifier(random_state=42),
    param_distributions=params_ada,
    n_iter=15,
    scoring="f1_macro",
    cv=5,
    random_state=42,
    n_jobs=-1
)

random_ada.fit(x_train, y_train)

model_ada = random_ada.best_estimator_
y_pre_ada = model_ada.predict(x_test)

print("Accuracy:", accuracy_score(y_test, y_pre_ada))
print(confusion_matrix(y_test, y_pre_ada))
print(classification_report(y_test, y_pre_ada))

Accuracy: 0.524396782841823
[[236 280]
 [607 742]]
              precision    recall  f1-score   support

           0       0.28      0.46      0.35       516
           1       0.73      0.55      0.63      1349

    accuracy                           0.52      1865
   macro avg       0.50      0.50      0.49      1865
weighted avg       0.60      0.52      0.55      1865

In [39]:
print("NaN in x_train:", x_train.isnull().sum().sum())
print("NaN in x_test:", x_test.isnull().sum().sum())
print("NaN in y_train:", y_train.isnull().sum())
print("NaN in y_test:", y_test.isnull().sum())

print("customer_id in x_train:", "customer_id" in x_train.columns)
print("customer_id in x_test:", "customer_id" in x_test.columns)

print("Same shape:", x_train.shape, x_test.shape)
print("Same columns:", (x_train.columns == x_test.columns).all())

print("Object cols in x_train:", x_train.select_dtypes(include="object").columns.tolist())
print("Object cols in x_test:", x_test.select_dtypes(include="object").columns.tolist())

print("y_train balance:")
print(y_train.value_counts())
print(y_train.value_counts(normalize=True))

NaN in x_train: 0
NaN in x_test: 0
NaN in y_train: 0
NaN in y_test: 0
customer_id in x_train: False
customer_id in x_test: False
Same shape: (5506, 35) (1865, 35)
Same columns: True
Object cols in x_train: []
Object cols in x_test: []
y_train balance:
loan_status
1    3441
0    2065
Name: count, dtype: int64
loan_status
1    0.624955
0    0.375045
Name: proportion, dtype: float64

In [40]:
print(cat_cols)
print(x_train.columns.tolist())
print(type(x_train))

['gender', 'marital_status', 'education_level', 'employment_type', 'loan_purpose', 'home_ownership']
['age', 'annual_income', 'loan_amount', 'credit_score', 'employment_years', 'debt_to_income_ratio', 'existing_loans', 'loan_term_months', 'interest_rate', 'gender_male', 'gender_other', 'gender_unknown', 'marital_status_married', 'marital_status_single', 'marital_status_unknown', 'marital_status_widowed', 'education_level_diploma', 'education_level_high school', 'education_level_master', 'education_level_phd', 'education_level_unknown', 'employment_type_part-time', 'employment_type_self-employed', 'employment_type_unemployed', 'employment_type_unknown', 'loan_purpose_car', 'loan_purpose_education', 'loan_purpose_home', 'loan_purpose_medical', 'loan_purpose_personal', 'loan_purpose_unknown', 'home_ownership_other', 'home_ownership_own', 'home_ownership_rent', 'home_ownership_unknown']
<class 'pandas.core.frame.DataFrame'>

In [41]:

print(pd.Series(y_train).value_counts())

loan_status
1    3441
0    2065
Name: count, dtype: int64

In [43]:
import joblib

model_xgb = {
    "model": model_xgb,
    "scaler": scaler,                         
    "num_cols": num_cols,
    "cat_cols": cat_cols,
    "final_columns": x_train.columns.tolist(),
    "label_map": {0: "Rejected", 1: "Approved"},
}

joblib.dump(model_xgb, "xgb_model.pkl")
print("Saved")

Saved

In [44]:


# Random Forest 
model_bundle_rf = {
    "model": model_rf,
    "scaler": scaler,
    "num_cols": num_cols,
    "cat_cols": cat_cols,
    "final_columns": x_train.columns.tolist(),
    "label_map": {0: "Rejected", 1: "Approved"},
}
joblib.dump(model_bundle_rf, "rf_model.pkl")
print("Saved: rf_model.pkl")


# AdaBoost
model_bundle_ada = {
    "model": model_ada,
    "scaler": scaler,
    "num_cols": num_cols,
    "cat_cols": cat_cols,
    "final_columns": x_train.columns.tolist(),
    "label_map": {0: "Rejected", 1: "Approved"},
}
joblib.dump(model_bundle_ada, "ada_model.pkl")
print("Saved: ada_model.pkl")

# Decision Tree
model_bundle_dt = {
    "model": model_dt,
    "scaler": scaler,
    "num_cols": num_cols,
    "cat_cols": cat_cols,
    "final_columns": x_train.columns.tolist(),
    "label_map": {0: "Rejected", 1: "Approved"},
}
joblib.dump(model_bundle_dt, "dt_model.pkl")
print("Saved: dt_model.pkl")

Saved: rf_model.pkl
Saved: ada_model.pkl
Saved: dt_model.pkl

In [ ]:
import joblib
joblib.dump(model_xgb, "xgb_model_1.pkl")
print("saved")

NameError: name 'model_xgb' is not defined

In [ ]:
from lightgbm import LGBMClassifier

params_lgbm = {
    "n_estimators": [100, 200, 300],
    "learning_rate": [0.01, 0.05, 0.1],
    "max_depth": [3, 5, 7],
    "num_leaves": [31, 63, 127],
    "class_weight": ["balanced"]
}

random_lgbm = RandomizedSearchCV(
    estimator=LGBMClassifier(random_state=42),
    param_distributions=params_lgbm,
    n_iter=30,
    scoring="f1_macro",
    cv=5,
    random_state=42,
    n_jobs=-1
)

random_lgbm.fit(x_train, y_train)
y_pre_lgbm = random_lgbm.predict(x_test)

print("Accuracy:", accuracy_score(y_test, y_pre_lgbm))
print(confusion_matrix(y_test, y_pre_lgbm))
print(classification_report(y_test, y_pre_lgbm))

In [ ]:
#split train, test
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42, stratify=y)

cat_cols = x_train.select_dtypes(include=["object", "string"]).columns.tolist()
num_cols = x_train.select_dtypes(include=["int64", "float64"]).columns.tolist()

#scale numeric features
scaler = StandardScaler()
x_train_num = pd.DataFrame(scaler.fit_transform(x_train[num_cols]), 
                           columns=num_cols, index=x_train.index
                           )
x_test_num = pd.DataFrame(scaler.transform(x_test[num_cols]),
                          columns=num_cols, index=x_test.index
                          )


#encode categorical features
x_train_cat = pd.get_dummies(x_train[cat_cols], drop_first=True, dtype=int)
x_test_cat = pd.get_dummies(x_test[cat_cols], drop_first=True, dtype=int)

# merge numeric and categorical features

x_train = pd.concat([x_train_num, x_train_cat], axis=1)
x_test = pd.concat([x_test_num, x_test_cat], axis=1)
from imblearn.under_sampling import RandomUnderSampler

rus = RandomUnderSampler(
    sampling_strategy=0.8,  
    random_state=42
)

x_train, y_train = rus.fit_resample(x_train, y_train)

print(y_train.value_counts())

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
# Predict the probability of Y base on our best threshold 
Y_valid_pred = np.where(y_pred_prob > best_thresholds, 1, 0) 

# Find the confusion matrix
cm = metrics.confusion_matrix(validationY,Y_valid_pred)

#Print out the confusion matrix in the context of pay - default 
df_cm = pd.DataFrame(data=cm, index = ['pay', 'default'], columns = ['pay', 'default'])
df_cm.index.name = 'TRUE'
df_cm.columns.name = 'PREDICTION'
print(f'Confusion matrix for the threshold of {best_thresholds}') 
df_cm

NameError: name 'y_pred_prob' is not defined

In [ ]:
def plot_confusion_matrix(cm, classes,
                          normalize=False,
                          title='Confusion matrix',
                          cmap=plt.cm.Blues):
    sns.set_style('white')

    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1, keepdims = True)

    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes)
    plt.yticks(tick_marks, classes)
    plt.tick_params(labeltop=True, labelbottom=False)

    fmt = '.2f' if normalize else 'd'
    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, format(cm[i, j], fmt),
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.tight_layout()
    plt.ylabel('True label') 
    #plt.XAxis.set_label_position('top')
    plt.xlabel('Predicted label', loc = 'center')

In [ ]:
class_names = ['pay', 'default']
plt.figure()
plot_confusion_matrix(cm, classes=class_names,
                      title='Confusion matrix, without normalization')

# Plot normalized confusion matrix
plt.figure()
plot_confusion_matrix(cm, classes=class_names, normalize=True,
                      title='Normalized confusion matrix')

plt.grid(False)

plt.show()

In [ ]:
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from imblearn.ensemble import BalancedBaggingClassifier
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
x, y = make_classification(
    n_samples=4500,
    n_features=20,
    n_classes=2,
    weights=[0.5, 0.5],
    n_informative=3,
    n_redundant=1,
    random_state=123
)

In [ ]:
np.sum(y == 0)

np.int64(2250)

In [ ]:
np.sum(y == 1)

np.int64(2250)

In [ ]:
df_pre = df_cleaned.drop(columns=["customer_id"])
x = df_pre.drop(columns=["loan_status"])
y = df_pre["loan_status"]

y = df_pre["loan_status"].str.strip().str.lower()
y = y.map({"rejected": 0, "approved": 1})

In [ ]:
cat_cols = x_train.select_dtypes(include=["object", "string"]).columns.tolist()
num_cols = x_train.select_dtypes(include=["int64", "float64"]).columns.tolist()

#scale nuSSSSmeric features
scaler = StandardScaler()
x_train_num = pd.DataFrame(scaler.fit_t#split train, test
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42, stratify=y)ransform(x_train[num_cols]), 
                           columns=num_cols, index=x_train.index
                           )
x_test_num = pd.DataFrame(scaler.transform(x_test[num_cols]),
                          columns=num_cols, index=x_test.index
                          )


#encode categorical features
x_train_cat = pd.get_dummies(x_train[cat_cols], drop_first=True, dtype=int)
x_test_cat = pd.get_dummies(x_test[cat_cols], drop_first=True, dtype=int)

# merge numeric and categorical features

X_train = pd.concat([x_train_num, x_train_cat], axis=1)
X_test = pd.concat([x_test_num, x_test_cat], axis=1)